using System.Text;

namespace Consultologist.Api.Workflow;

/// <summary>
/// Derives a Mermaid flowchart from a manifest's nodes. Bindings are the edges plus
/// strictly more, so the diagram is always generated and never authored — the
/// derived-view rule that rejected a second edge file. forEach chains render as a
/// per-collection subgraph: the container lives on as presentation, never as format
/// (docs/customizable-workflow/package-format-v5.md). The checked-in
/// The general package's dag.mmd (consultologist-workflows repo) is generated by this generator.
/// </summary>
public static class WorkflowDagDiagram
{
    public static string Generate(WorkflowPackageManifest manifest)
    {
        var nodes = manifest.Nodes
            ?? throw new InvalidOperationException(
                $"Package {manifest.Name}@{manifest.Version} declares no nodes; the DAG diagram requires specVersion 5.");

        var sb = new StringBuilder();
        sb.Append("flowchart TD\n");

        // External sources first, in first-reference order: engine inputs, scalar
        // data entries, and forEach collections all render as stadiums.
        foreach (var source in CollectExternalSources(nodes))
        {
            sb.Append($"    {Sanitize(source)}([\"{source}\"])\n");
        }

        sb.Append('\n');

        var nodesById = nodes.ToDictionary(node => node.Id, StringComparer.Ordinal);

        foreach (var node in nodes.Where(node => node.ForEach is null))
        {
            if (node.Aggregate != null)
            {
                // Aggregators are graph-visible by construction: their own box, one
                // labeled edge per source in declared order (v6, aggregator nodes).
                sb.Append($"    {Sanitize(node.Id)}[\"{node.Id}<br/>{node.Label}<br/>aggregate\"]\n");

                foreach (var sourceRef in node.Aggregate)
                {
                    var sourceId = sourceRef.StartsWith(WorkflowNodeBindingSources.NodePrefix, StringComparison.Ordinal)
                        ? sourceRef[WorkflowNodeBindingSources.NodePrefix.Length..]
                        : sourceRef;
                    sb.Append($"    {Sanitize(sourceId)} -->|\"aggregate\"| {Sanitize(node.Id)}\n");
                }

                continue;
            }

            var label = $"{node.Id}<br/>{node.Label}";
            if (node.Output != null)
            {
                label += $"<br/>output: {node.Output.Schema}";
            }

            sb.Append($"    {Sanitize(node.Id)}[\"{label}\"]\n");

            foreach (var (variable, binding) in node.Bindings ?? new Dictionary<string, WorkflowBindingValue>())
            {
                AppendEdge(sb, binding, variable, Sanitize(node.Id), indent: "    ");
            }
        }

        foreach (var collection in nodes
            .Where(node => node.ForEach != null)
            .Select(node => node.ForEach!)
            .Distinct(StringComparer.Ordinal))
        {
            var chain = nodes.Where(node => string.Equals(node.ForEach, collection, StringComparison.Ordinal)).ToList();
            var subgraphId = "foreach_" + Sanitize(collection);

            bool IsItemAligned(WorkflowBindingValue binding) =>
                binding.From.StartsWith(WorkflowNodeBindingSources.NodePrefix, StringComparison.Ordinal)
                && nodesById.TryGetValue(binding.From[WorkflowNodeBindingSources.NodePrefix.Length..], out var target)
                && string.Equals(target.ForEach, collection, StringComparison.Ordinal);

            sb.Append('\n');
            sb.Append($"    {Sanitize(collection)} -->|\"forEach\"| {subgraphId}\n");
            sb.Append($"    subgraph {subgraphId}[\"per {collection} item\"]\n");

            foreach (var node in chain)
            {
                var itemFields = (node.Bindings ?? new Dictionary<string, WorkflowBindingValue>())
                    .Values
                    .Where(binding => binding.From.StartsWith("item:", StringComparison.Ordinal))
                    .Select(binding => binding.From["item:".Length..])
                    .Distinct(StringComparer.Ordinal)
                    .ToList();
                var label = $"{node.Id}<br/>{node.Label}";
                if (itemFields.Count > 0)
                {
                    label += $"<br/>item: {string.Join(", ", itemFields)}";
                }

                sb.Append($"        {Sanitize(node.Id)}[\"{label}\"]\n");
            }

            // Item-aligned edges (same-collection node: bindings) live inside the box.
            foreach (var node in chain)
            {
                foreach (var (variable, binding) in node.Bindings ?? new Dictionary<string, WorkflowBindingValue>())
                {
                    if (IsItemAligned(binding))
                    {
                        AppendEdge(sb, binding, variable, Sanitize(node.Id), indent: "        ");
                    }
                }
            }

            sb.Append("    end\n");

            // Broadcast and input edges cross the boundary from outside, keeping the
            // subgraph box tight.
            foreach (var node in chain)
            {
                foreach (var (variable, binding) in node.Bindings ?? new Dictionary<string, WorkflowBindingValue>())
                {
                    if (!IsItemAligned(binding))
                    {
                        AppendEdge(sb, binding, variable, Sanitize(node.Id), indent: "    ");
                    }
                }
            }
        }

        return sb.ToString();
    }

    private static void AppendEdge(
        StringBuilder sb,
        WorkflowBindingValue binding,
        string variable,
        string targetId,
        string indent)
    {
        string sourceId;

        if (binding.From.StartsWith(WorkflowNodeBindingSources.NodePrefix, StringComparison.Ordinal))
        {
            sourceId = Sanitize(binding.From[WorkflowNodeBindingSources.NodePrefix.Length..]);
        }
        else if (binding.From.StartsWith("input:", StringComparison.Ordinal)
            || binding.From.StartsWith(WorkflowNodeBindingSources.DataPrefix, StringComparison.Ordinal))
        {
            sourceId = Sanitize(binding.From);
        }
        else
        {
            return; // item:* fields live in the node label.
        }

        var label = binding.As is null ? variable : $"{variable} (as {binding.As})";
        sb.Append($"{indent}{sourceId} -->|\"{label}\"| {targetId}\n");
    }

    private static IReadOnlyList<string> CollectExternalSources(IReadOnlyList<WorkflowNodeSpec> nodes)
    {
        var sources = new List<string>();

        void Add(string? from)
        {
            if (from != null
                && (from.StartsWith("input:", StringComparison.Ordinal) || from.StartsWith(WorkflowNodeBindingSources.DataPrefix, StringComparison.Ordinal))
                && !sources.Contains(from))
            {
                sources.Add(from);
            }
        }

        foreach (var node in nodes)
        {
            foreach (var binding in (node.Bindings ?? new Dictionary<string, WorkflowBindingValue>()).Values)
            {
                Add(binding.From);
            }

            Add(node.ForEach);
        }

        return sources;
    }

    private static string Sanitize(string raw)
        => new(raw.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());
}
